# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ASWF Sample Project
#
# A simple Azure Pipelines YAML setup to build and upload a Windows based container
#

trigger:
- master

jobs:

- job: Windows
  pool:
    vmImage: 'win1803'

  steps:
  - task: Docker@2
    inputs:
      command: build
      repository: panisset/buildtools2019
      tags: latest
      arguments: -m 2GB
    displayName: Docker Build
  - task: Docker@2
    inputs:
      command: login
      containerRegistry: windows-container-test.dockerhub.connection
    displayName: Docker Hub Login
  - task: Docker@2
    inputs:
      command: push
      containerRegistry: windows-container-test.dockerhub.connection
      repository: panisset/buildtools2019
      tags: latest
    displayName: Docker Push


