# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ASWF Sample Project
#
# A simple multi-platform Azure Pipelines definition to build, run test suite
# and upload results to test dashboard. Using 'matrix' would reduce duplication
# but there's no such thing as macOS containers. Could move the steps to a separate
# YAML file.

trigger:
- master

jobs:

- job: Windows
  pool:
    vmImage: 'win1803'

  steps:
  - script: |
      docker build -t buildtools2019:latest -m 2GB --build-arg FROM_IMAGE=mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-1803 .
    displayName: Docker Build
  - script: |
      docker login -u $(DOCKER_HUB_USERNAME) -p $(DOCKER_HUB_PASSWORD)
    displayName: Docker Hub Login
    env:
      DOCKER_HUB_USERNAME: $(DOCKER_HUB_USERNAME)
      DOCKER_HUB_PASSWORD: $(DOCKER_HUB_PASSWORD)
  - script: |
      docker tag buildtools2019:latest $(DOCKER_HUB_USERNAME)/buildtools2019:latest
      docker push $(DOCKER_HUB_USERNAME)/buildtools2019
    displayName: Docker Push
    env:
      DOCKER_HUB_USERNAME: $(DOCKER_HUB_USERNAME)

