# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ASWF Sample Project
#
# A simple GitHub Actions pipeline to build a Windows build container and upload to Docker Hub
#

name: Windows Build Container

on: [push]

jobs:
  Windows-Build-Container:
    runs-on: windows-2022
    container: 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push
        run: |
          docker build -t panisset/aswf-docker-win:latest .
          docker push panisset/aswf-docker-win:latest


